### ISSUE TITLE
Prequential Evaluation Error - "number of items to replace is not a multiple of replacement length"

### ISSUE THREAD

**Issue by sabriel330** [jwijffels/RMOA#10]
When implementing prequential evaluation (test first, then train) using RMOA, I encounter the following error when making predictions:

> "number of items to replace is not a multiple of replacement length"

For some reason this only occurs when more than one class label is observed.  The issue seems to stem from the `getVotesForInstance()` method since this error is thrown:

> Error in scores[j, ] <- object$moamodel$getVotesForInstance()

[This pastebin](https://pastebin.com/A3hJjcWB) contains my source.

Do you have a fix for this?

**Comment by jwijffels** [comment]
You need to use RMOA version 1.1 (on CRAN you have version 1.0). This was fixed in commit https://github.com/jwijffels/RMOA/commit/39665f9c721af8c0a93e1122d26fe475652baa26.

`install_github("jwijffels/RMOA", subdir="RMOA/pkg")`
