### ISSUE TITLE
No man pages found in package

### ISSUE THREAD

**Issue by Dima-Ramadan** [jwijffels/RMOA#16]
I'm trying to install the package but I get 
"No man pages found in package 'RMOAjars' "
How can fix this? 

The problem appears like this 

Downloading GitHub repo jwijffels/RMOA@HEAD
√  checking for file 'C:\AppData\Local\Temp\RtmpqcXqgZ\remotes36506fb26e21\jwijffels-RMOA-e02490e\RMOAjars\pkg/DESCRIPTION' (869ms)
-  preparing 'RMOAjars':
√  checking DESCRIPTION meta-information
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'RMOAjars_1.2.0.tar.gz'
   
Installing package into ‘C:/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'RMOAjars' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  'RMOAjars' 
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'RMOAjars':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Documents/R/win-library/4.1/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Documents/R/win-library/4.1/RMOAjars'

**Comment by jwijffels** [comment]
Please just install the package from CRAN instead of github and make sure you have java correctly installed. You can ask these type of questions on stackoverflow, as they are not related to this R package but your java setup
