### ISSUE TITLE
Test then train

### ISSUE THREAD

**Issue by ahara** [jwijffels/RMOA#4]
Is it possible to achieve in RMOA similar effect to EvaluateInterleavedTestThenTrain from MOA?

I'd like to e.g. test model on sample[i+x] then train on sample[i] and so on.

**Comment by jwijffels** [comment]
Yes of course, just use one of the many data stream options that are available in RMOA to connect to your dataset which is a data.frame, ff, matrix, csv or flatfile, json, ... and in the trainMOA pass on the sample[i] data, predict on the sample[i+x] and use one of the many thousands of evaluation metrics which other packages like ROCR or caret provides to see how good your prediction is.

**Comment by ahara** [comment]
Thank you.
