### ISSUE TITLE
Saving trained model

### ISSUE THREAD

**Issue by miranska** [jwijffels/RMOA#5]
Thank you for the package! Is it possible to save trained model to disk? It seems that R's `save` function cannot capture Java environment properly.

**Comment by jwijffels** [comment]
Yes, you can save these models to disk similarly as you would save a java model. 
An example is shown in the RWeka library https://cran.r-project.org/web/packages/RWeka/vignettes/RWeka.pdf

Basically, you need to use rJava::.jcache

**Comment by miranska** [comment]
Thank you! I’ll give it a try.
