### ISSUE TITLE
Number of factor levels during training

### ISSUE THREAD

**Issue by miranska** [jwijffels/RMOA#6]
It seems that `trainMOA` experiences issues during incremental learning, when the number of factors in the new record set is lower that the number of factors in the original record set. Could you please tell me, is there a way around this? Consider this toy example: 

```R
require(RMOA)

dat <- data.frame( a = c("a", "a", "b"),
                   b = c("a", "b", "c"))

ctrl <- MOAoptions(model = "DACC", randomSeed = 123456789)
mdl <- trainMOA(model = DACC(control = ctrl)
     , formula = a ~ b
     , data = datastream_dataframe(dat)
     , chunksize = 1
     , trace = T 
     , reset = F 
)

dat.new <- data.frame( a = c("a", "b", "b"), 
                       b = c("d", "e", "e"))

mdl.new <- trainMOA(model = mdl$model
                , formula = a ~ b
                , data = datastream_dataframe(dat.new)
                , chunksize = 1
                , trace = T
                , reset = F
)

#The above line will generate the following error:
# 2016-10-13 20:17:39 Running chunk 1: instances 0:1
# Error in .jcall(model$moamodel, "V", "prepareForUse") : 
# java.lang.IllegalArgumentException: New context is not compatible with existing model

# However, adding one extra factor to dat.new$b makes the problem disappear:
dat.new <- data.frame( a = c("a", "b", "b"), 
                       b = c("d", "e", "f"))

mdl.new <- trainMOA(model = mdl$model
                    , formula = a ~ b
                    , data = datastream_dataframe(dat.new)
                    , chunksize = 1
                    , trace = T 
                    , reset = F 
)

```

**Comment by jwijffels** [comment]
You have to make sure your factor levels are the same across training / scoring.
For this, you have the transFUN argument of trainMOA. See the help of trainMOA where it is explicitely stated that the factor levels should be the same. Use the transFUN argument to fix this as in 

```
transFUN=function(x){
x$mycolumn <- factor(x$mycolumn, levels = c("a", "b", "c", "d", "..."))
x
}
```

**Comment by miranska** [comment]
Magic! We've been playing around with appending the levels to the data frame directly, but were not certain if it will corrupt the model. **Could you please verify the code below?**  Is this the correct approach for our toy example?

```R
transFun <- function(x){
  x$b <- factor(x$b, levels = c("a", "b", "c", "d", "e", "f"))
  x
}

mdl.new <- trainMOA(model = mdl$model
                    , formula = a ~ b
                    , data = datastream_dataframe(dat.new)
                    , transFUN = transFun
                    , chunksize = 1
                    , trace = T
                    , reset = F
)
```

**Comment by jwijffels** [comment]
In this case yes as the column a in the toy example has the same levels in both sessions.
What you need to do is apply transfun when you construct mdl  and also when you construct mdl.new

**Comment by miranska** [comment]
A! So all the levels have to be known from the very beginning, right? This is an issue for production use cases, as we may not know all the levels in advance in case of the incremental learning on streaming data. 

This is the issue that we currently face. For example, if `b` represents an IP address from which a network packet has originated, we need to create a list of all possible IP addresses, which is prohibitively expensive from practical perspective (as there are 2^128 IPv6 addresses).

Could you please tell me, is this a limitation of RMOA or MOA itself?

**Comment by jwijffels** [comment]
This is a limitation of RMOA. in MOA there is functionality to add new levels but the complexity of implementing is a bit too high and surely would even decrease speed.
RMOA maps the levels with model.matrix to binary flags and that depends on the order of the levels. You should check if new levels can be added if the integer values of the level is bigger than the existing ones. This has not been tested currently however.

**Comment by miranska** [comment]
Thank you for the help! We will explore the source code.
